"""empty message

Revision ID: 525935687efd
Revises: 97445f0d0c7a
Create Date: 2022-03-23 08:00:39.566762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525935687efd'
down_revision = '97445f0d0c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reader_book',
    sa.Column('reader_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['reader_id'], ['reader.id'], )
    )
    op.drop_index('ix_book_title', table_name='book')
    op.create_index(op.f('ix_book_title'), 'book', ['title'], unique=True)
    op.drop_constraint('book_user_id_fkey', 'book', type_='foreignkey')
    op.drop_column('book', 'user_id')
    op.drop_index('ix_reader_email', table_name='reader')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_reader_email', 'reader', ['email'], unique=False)
    op.add_column('book', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('book_user_id_fkey', 'book', 'reader', ['user_id'], ['id'])
    op.drop_index(op.f('ix_book_title'), table_name='book')
    op.create_index('ix_book_title', 'book', ['title'], unique=False)
    op.drop_table('reader_book')
    # ### end Alembic commands ###
