"""empty message

Revision ID: a973f466b8cd
Revises: dd42aefd3d71
Create Date: 2022-03-23 14:40:06.820942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a973f466b8cd'
down_revision = 'dd42aefd3d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_book_author', table_name='book')
    op.drop_index('ix_book_title', table_name='book')
    op.alter_column('reader', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reader', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.create_index('ix_book_title', 'book', ['title'], unique=False)
    op.create_index('ix_book_author', 'book', ['author'], unique=False)
    # ### end Alembic commands ###
