"""empty message

Revision ID: d0a6a42e72c7
Revises: a973f466b8cd
Create Date: 2022-03-23 14:55:35.158752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a6a42e72c7'
down_revision = 'a973f466b8cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_book_date_added'), 'book', ['date_added'], unique=False)
    op.alter_column('reader', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_constraint('reader_book_book_id_fkey', 'reader_book', type_='foreignkey')
    op.create_foreign_key(None, 'reader_book', 'book', ['book_id'], ['book_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reader_book', type_='foreignkey')
    op.create_foreign_key('reader_book_book_id_fkey', 'reader_book', 'book', ['book_id'], ['id'])
    op.alter_column('reader', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_index(op.f('ix_book_date_added'), table_name='book')
    # ### end Alembic commands ###
